### ISSUE TITLE
Is this working on Android M?

### ISSUE THREAD

**Issue by marcelvoss95** [jd-alexander/ScreenWatch#1]
Is this working on Android M?
I heard File Observer does not work on Android 6.0

https://code.google.com/p/android/issues/detail?id=189231&q=fileobserver&colspec=ID%20Status%20Priority%20Owner%20Summary%20Stars%20Reporter%20Opened

**Comment by jd-alexander** [comment]
Well based on that it's not. I never got this project completed and in any case you can just use a ContentObserver to perform the same task.
